version: '2'
services:
    personal_data-app:
        image: jreyesromero/personal_data
        external_links:
            - data-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/personal_data?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10
            - JHIPSTER_REGISTRY_PASSWORD=undefined
        ports:
            - 8080:8080
    student_info-app:
        image: jreyesromero/student_info
        external_links:
            - data-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/student_info?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10
            - JHIPSTER_REGISTRY_PASSWORD=undefined
        ports:
            - 8081:8081
    data-mysql:
        container_name: data-mysql
        image: mysql:5.7.13
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=student_info
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
    


